name: alpha2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^3.3.4
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.6
  google_mlkit_text_recognition: ^0.14.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.13.1

  flutter_image_compress: ^2.3.0
  flutter_secure_storage: ^9.0.0
  crop_image: ^1.0.15
  image_cropper: ^5.0.1
  intl: ^0.19.0
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/playstore-icon.png"



flutter:
  uses-material-design: true
  assets:
    - assets/pixelcut-export.jpeg 
  

  